### PR TITLE
Fixes and Additions!

### PR DESCRIPTION
**Pull request by possibIy**
+FOV_SHOW
=FIXED GREEN COLOR
=FIXED LOADING
=FIXED HIDE_CONSOLE

### CODE REVIEW

**Comment by Seconb** [comment]
Awesome, I’ll probably add this I just need to change two things (you removed some of the banner that prints, and you modified the green color which breaks it on Arsenal). Not at my PC so i’ll handle it in the morning

**Comment by possibIy** [comment]
Okay! I removed banner just cause it was easier for me to read config and for color I was messing with the Roblox "ESP" FFlag which is green. On Arsenal I just use Red. But sounds good! Thanks.

**Comment by possibIy** [comment]
Just wanted to let you know before tomorrow I also removed update check for my own good. So make sure to add that back (out of ''' ''')!

**Comment by Seconb** [comment]
got it 👍

**Comment by Seconb** [comment]
Added the features and credited you in the readme. Thank you!

**Pull request closed without merging**
